# Implementing the word embeddings with Tensorflow and Keras


In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
from tensorflow.keras.preprocessing.text import one_hot

### Example sentences

In [3]:

sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

## Define Vocabulary Size

In [4]:
vocabulary_size = 10000

## One Hot representation of every words

In [5]:
one_hot_representation =  [one_hot(input_text= words,
                                   n= vocabulary_size,
                                   lower = True,
                                   filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n')
                            for words in sent]

one_hot_representation


[[5347, 83, 5599, 4897],
 [5347, 83, 5599, 3031],
 [5347, 4912, 5599, 681],
 [2280, 3019, 181, 4622, 6066],
 [2280, 3019, 181, 4622, 2860],
 [5787, 5347, 8083, 5599, 6811],
 [469, 4463, 837, 4622]]

each word is assigned a specfic index in the vocabulary size of 10000, ex: the -> 8798

## Word Embedding representation

In [6]:
from tensorflow.keras.layers import Embedding,Input
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot

#### pad_sequence is used to set the maximum number of words in sentences as it is neccessary to train a model that each sentences has equal number of words

In [7]:
sent_length = 8

embedded_docs = pad_sequences(sequences = one_hot_representation,
                              maxlen = sent_length,
                              padding ="pre")
embedded_docs


array([[   0,    0,    0,    0, 5347,   83, 5599, 4897],
       [   0,    0,    0,    0, 5347,   83, 5599, 3031],
       [   0,    0,    0,    0, 5347, 4912, 5599,  681],
       [   0,    0,    0, 2280, 3019,  181, 4622, 6066],
       [   0,    0,    0, 2280, 3019,  181, 4622, 2860],
       [   0,    0,    0, 5787, 5347, 8083, 5599, 6811],
       [   0,    0,    0,    0,  469, 4463,  837, 4622]], dtype=int32)

* before:

[8798, 7581, 9522, 2220],

[5799, 6775, 4816, 1279, 9480],


* after pre-padding:

[   0,    0,    0,    0, 8798, 7581, 9522, 2220],

[   0,    0,    0, 5799, 6775, 4816, 1279, 9480],


* after post-padding:

[8798, 7581, 9522, 2220,    0,    0,    0,    0],

[5799, 6775, 4816, 1279, 9480,    0,    0,    0],

## feature representation

In [8]:
dim = 10

In [9]:
model = Sequential()

model.add(Embedding(input_dim= vocabulary_size,
                    output_dim = dim,
                    input_length = sent_length))

model.compile(optimizer= "adam",
              loss = "mse")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

Embedding

(None, sent_length, dim)

Params = vocabulary_size × dim

In [11]:
# from keras.models import Sequential
# from keras.layers import Embedding, Input

# model = Sequential([
#     Input(shape=(sent_length,)),
#     Embedding(
#         input_dim=vocabulary_size,
#         output_dim=dim
#     )
# ])

# model.summary()

### Embedding internally use Word2Vec

## predict

In [13]:
word_embeddings = model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


In [14]:
word_embeddings

array([[[-0.02544025, -0.03359841,  0.00771732,  0.02625583,
         -0.02365254,  0.01752323, -0.03525754,  0.03988044,
          0.03839057, -0.02985075],
        [-0.02544025, -0.03359841,  0.00771732,  0.02625583,
         -0.02365254,  0.01752323, -0.03525754,  0.03988044,
          0.03839057, -0.02985075],
        [-0.02544025, -0.03359841,  0.00771732,  0.02625583,
         -0.02365254,  0.01752323, -0.03525754,  0.03988044,
          0.03839057, -0.02985075],
        [-0.02544025, -0.03359841,  0.00771732,  0.02625583,
         -0.02365254,  0.01752323, -0.03525754,  0.03988044,
          0.03839057, -0.02985075],
        [ 0.00495126,  0.04228835, -0.04527987,  0.04743655,
         -0.0152601 ,  0.02083751,  0.04271413, -0.04687954,
         -0.04912592, -0.01755289],
        [-0.03088855,  0.02581546,  0.01236521, -0.00356011,
         -0.01360102,  0.0143779 ,  0.03234409,  0.00984668,
          0.0488969 ,  0.04655482],
        [ 0.02296909,  0.00689132,  0.00708402, -0.0

### comparison

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 5347,   83, 5599, 4897], dtype=int32)

In [17]:
word_embeddings[0][0]

array([-0.02544025, -0.03359841,  0.00771732,  0.02625583, -0.02365254,
        0.01752323, -0.03525754,  0.03988044,  0.03839057, -0.02985075],
      dtype=float32)